# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)
Category.create!([{name: 'Sleep & Relaxation'},
                  {name: 'Time with Katie'},
                  {name: 'Social'},
                  {name: 'Social Work'},
                  {name: 'Solo Work'},
                  {name: 'Personal Work'},
                  {name: 'Solo Entertainment'},
                  {name: 'Physical'},
                  {name: 'Spiritual'},
                  {name: 'Everyday tasks'},
                  {name: 'Development & Leadership'}])

Activity.create!([{name: 'Sleep', category_id: Category.find_by_name('Sleep & Relaxation').id, repeating: TRUE, old_id:1},
                  {name: 'Almost Sleep', category_id: Category.find_by_name('Sleep & Relaxation').id, repeating: TRUE, old_id:2},
                  {name: 'Meditate', category_id: Category.find_by_name('Sleep & Relaxation').id, repeating: TRUE, old_id:3},
                  {name: 'Katie: Having fun', category_id: Category.find_by_name('Time with Katie').id, repeating: TRUE, old_id:4},
                  {name: 'Katie: Concert Movie Art', category_id: Category.find_by_name('Time with Katie').id, repeating: TRUE, old_id:53},
                  {name: 'Katie: Talking', category_id: Category.find_by_name('Time with Katie').id, repeating: TRUE, old_id:5},
                  {name: 'Katie: Making out', category_id: Category.find_by_name('Time with Katie').id, repeating: TRUE, old_id:6},
                  {name: 'Katie: Working together', category_id: Category.find_by_name('Time with Katie').id, repeating: TRUE, old_id:7},
                  {name: 'Katie: Eating together', category_id: Category.find_by_name('Time with Katie').id, repeating: TRUE, old_id:8},
                  {name: 'Katie: Sitting together', category_id: Category.find_by_name('Time with Katie').id, repeating: TRUE, old_id:9},
                  {name: 'Katie: Spiritual together', category_id: Category.find_by_name('Time with Katie').id, repeating: TRUE, old_id:10},
                  {name: 'Katie: Working out/walking', category_id: Category.find_by_name('Time with Katie').id, repeating: TRUE, old_id:11},
                  {name: 'Katie: Doing things for her', category_id: Category.find_by_name('Time with Katie').id, repeating: TRUE, old_id:12},
                  {name: 'Katie: Time with friends', category_id: Category.find_by_name('Social').id, repeating: TRUE, old_id:13},
                  {name: 'Time with Family', category_id: Category.find_by_name('Social').id, repeating: TRUE, old_id:15},
                  {name: 'Time with friends: Talking on the phone', category_id: Category.find_by_name('Social').id, repeating: TRUE, old_id:16},
                  {name: 'Time with friends: Concert Movie Art', category_id: Category.find_by_name('Social').id, repeating: TRUE, old_id:17},
                  {name: 'Time with friends: Weekday hanging out', category_id: Category.find_by_name('Social').id, repeating: TRUE, old_id:18},
                  {name: 'Time with friends: Weekend hanging out', category_id: Category.find_by_name('Social').id, repeating: TRUE, old_id:19},
                  {name: 'Time with friends: Sunday hanging out', category_id: Category.find_by_name('Social').id, repeating: TRUE, old_id:20},
                  {name: 'Time with friends: Social Planning', category_id: Category.find_by_name('Social').id, repeating: TRUE, old_id:21},
                  {name: 'Time with friends: Email Chatting Facebook', category_id: Category.find_by_name('Social').id, repeating: TRUE, old_id:22},
                  {name: 'Accounting', category_id: Category.find_by_name('Solo Work').id, repeating: TRUE, old_id:25},
                  {name: 'Finance and Planning', category_id: Category.find_by_name('Solo Work').id, repeating: TRUE, old_id:26},
                  {name: 'Extra Projects', category_id: Category.find_by_name('Solo Work').id, repeating: TRUE, old_id:27},
                  {name: 'Meetings', category_id: Category.find_by_name('Social Work').id, repeating: TRUE, old_id:28},
                  {name: 'Email', category_id: Category.find_by_name('Social Work').id, repeating: TRUE, old_id:29},
                  {name: 'Networking', category_id: Category.find_by_name('Social Work').id, repeating: TRUE, old_id:30},
                  {name: 'New Projects', category_id: Category.find_by_name('Social Work').id, repeating: TRUE, old_id:31},
                  {name: 'Development Learning', category_id: Category.find_by_name('Solo Work').id, repeating: TRUE, old_id:24},
                  {name: 'Programming', category_id: Category.find_by_name('Solo Work').id, repeating: TRUE, old_id:48},
                  {name: 'Sales & Marketing', category_id: Category.find_by_name('Social Work').id, repeating: TRUE, old_id:57},
                  {name: 'Web Design', category_id: Category.find_by_name('Solo Work').id, repeating: TRUE, old_id:55},
                  {name: 'Management', category_id: Category.find_by_name('Social Work').id, repeating: TRUE, old_id:56},
                  {name: 'Commute', category_id: Category.find_by_name('Personal Work').id, repeating: TRUE, old_id:32},
                  {name: 'Personal Finance', category_id: Category.find_by_name('Personal Work').id, repeating: TRUE, old_id:33},
                  {name: 'Calendar', category_id: Category.find_by_name('Development & Leadership').id, repeating: TRUE, old_id:34},
                  {name: 'Design', category_id: Category.find_by_name('Development & Leadership').id, repeating: TRUE, old_id:35},
                  {name: 'Singing', category_id: Category.find_by_name('Development & Leadership').id, repeating: TRUE, old_id:36},
                  {name: 'Clean', category_id: Category.find_by_name('Personal Work').id, repeating: TRUE, old_id:37},
                  {name: 'Shop', category_id: Category.find_by_name('Personal Work').id, repeating: TRUE, old_id:38},
                  {name: 'Scriptures', category_id: Category.find_by_name('Spiritual').id, repeating: TRUE, old_id:39},
                  {name: 'Church', category_id: Category.find_by_name('Spiritual').id, repeating: TRUE, old_id:40},
                  {name: 'Leadership Service', category_id: Category.find_by_name('Development & Leadership').id, repeating: TRUE, old_id:41},
                  {name: 'Journal Photos', category_id: Category.find_by_name('Development & Leadership').id, repeating: TRUE, old_id:42},
                  {name: 'Exercise', category_id: Category.find_by_name('Physical').id, repeating: TRUE, old_id:43},
                  {name: 'getready', category_id: Category.find_by_name('Physical').id, repeating: TRUE, old_id:44},
                  {name: 'Eating alone', category_id: Category.find_by_name('Physical').id, repeating: TRUE, old_id:45},
                  {name: 'Read wsj or bus mag', category_id: Category.find_by_name('Solo Entertainment').id, repeating: TRUE, old_id:46},
                  {name: 'Internet surfing', category_id: Category.find_by_name('Solo Entertainment').id, repeating: TRUE, old_id:47},
                  {name: 'Time Wasters', category_id: Category.find_by_name('Solo Entertainment').id, repeating: TRUE, old_id:49},
                  {name: 'Music', category_id: Category.find_by_name('Solo Entertainment').id, repeating: TRUE, old_id:50},
                  {name: 'Concert or Movie', category_id: Category.find_by_name('Solo Entertainment').id, repeating: TRUE, old_id:51},
                  {name: 'Reading', category_id: Category.find_by_name('Solo Entertainment').id, repeating: TRUE, old_id:54},
                  {name: 'Experience New York', category_id: Category.find_by_name('Solo Entertainment').id, repeating: TRUE, old_id:52},
                 ])
#Window.create!([{day_of_week: 6, activity_id: Activity.find_by_name('Katie: Having fun').id, end_time: 23, begin_time: 13},
#                {day_of_week: 0, activity_id: Activity.find_by_name('Katie: Having fun').id, end_time: 23, begin_time: 19},
#                {day_of_week: 1, activity_id: Activity.find_by_name('Katie: Having fun').id, end_time: 23, begin_time: 19},
#                {day_of_week: 2, activity_id: Activity.find_by_name('Katie: Having fun').id, end_time: 23, begin_time: 19},
#                {day_of_week: 3, activity_id: Activity.find_by_name('Katie: Having fun').id, end_time: 23, begin_time: 19},
#                {day_of_week: 4, activity_id: Activity.find_by_name('Katie: Having fun').id, end_time: 23, begin_time: 19},
#                {day_of_week: 5, activity_id: Activity.find_by_name('Katie: Having fun').id, end_time: 23, begin_time: 8},
#                {day_of_week: 6, activity_id: Activity.find_by_name('Katie: Concert Movie Art').id, end_time: 23, begin_time: 13},
#                {day_of_week: 0, activity_id: Activity.find_by_name('Katie: Concert Movie Art').id, end_time: 23, begin_time: 19},
#                {day_of_week: 1, activity_id: Activity.find_by_name('Katie: Concert Movie Art').id, end_time: 23, begin_time: 19},
#                {day_of_week: 2, activity_id: Activity.find_by_name('Katie: Concert Movie Art').id, end_time: 23, begin_time: 19},
#                {day_of_week: 3, activity_id: Activity.find_by_name('Katie: Concert Movie Art').id, end_time: 23, begin_time: 19},
#                {day_of_week: 4, activity_id: Activity.find_by_name('Katie: Concert Movie Art').id, end_time: 23, begin_time: 19},
#                {day_of_week: 5, activity_id: Activity.find_by_name('Katie: Concert Movie Art').id, end_time: 23, begin_time: 8},
#                {day_of_week: 6, activity_id: Activity.find_by_name('Katie: Talking').id, end_time: 23, begin_time: 13},
#                {day_of_week: 0, activity_id: Activity.find_by_name('Katie: Talking').id, end_time: 23, begin_time: 19},
#                {day_of_week: 1, activity_id: Activity.find_by_name('Katie: Talking').id, end_time: 23, begin_time: 19},
#                {day_of_week: 2, activity_id: Activity.find_by_name('Katie: Talking').id, end_time: 23, begin_time: 19},
#                {day_of_week: 3, activity_id: Activity.find_by_name('Katie: Talking').id, end_time: 23, begin_time: 19},
#                {day_of_week: 4, activity_id: Activity.find_by_name('Katie: Talking').id, end_time: 23, begin_time: 19},
#                {day_of_week: 5, activity_id: Activity.find_by_name('Katie: Talking').id, end_time: 23, begin_time: 8},
#                {day_of_week: 6, activity_id: Activity.find_by_name('Katie: Making out').id, end_time: 23, begin_time: 13},
#                {day_of_week: 0, activity_id: Activity.find_by_name('Katie: Making out').id, end_time: 23, begin_time: 19},
#                {day_of_week: 1, activity_id: Activity.find_by_name('Katie: Making out').id, end_time: 23, begin_time: 19},
#                {day_of_week: 2, activity_id: Activity.find_by_name('Katie: Making out').id, end_time: 23, begin_time: 19},
#                {day_of_week: 3, activity_id: Activity.find_by_name('Katie: Making out').id, end_time: 23, begin_time: 19},
#                {day_of_week: 4, activity_id: Activity.find_by_name('Katie: Making out').id, end_time: 23, begin_time: 19},
#                {day_of_week: 5, activity_id: Activity.find_by_name('Katie: Making out').id, end_time: 23, begin_time: 8},
#                {day_of_week: 0, activity_id: Activity.find_by_name('Katie: Working together').id, end_time: 23, begin_time: 19},
#                {day_of_week: 1, activity_id: Activity.find_by_name('Katie: Working together').id, end_time: 23, begin_time: 19},
#                {day_of_week: 2, activity_id: Activity.find_by_name('Katie: Working together').id, end_time: 23, begin_time: 19},
#                {day_of_week: 3, activity_id: Activity.find_by_name('Katie: Working together').id, end_time: 23, begin_time: 19},
#                {day_of_week: 4, activity_id: Activity.find_by_name('Katie: Working together').id, end_time: 23, begin_time: 19},
#                {day_of_week: 5, activity_id: Activity.find_by_name('Katie: Working together').id, end_time: 23, begin_time: 8},
#                {day_of_week: 6, activity_id: Activity.find_by_name('Katie: Eating together').id, end_time: 21, begin_time: 18},
#                {day_of_week: 6, activity_id: Activity.find_by_name('Katie: Eating together').id, end_time: 15, begin_time: 13},
#                {day_of_week: 0, activity_id: Activity.find_by_name('Katie: Eating together').id, end_time: 21, begin_time: 18},
#                {day_of_week: 1, activity_id: Activity.find_by_name('Katie: Eating together').id, end_time: 21, begin_time: 18},
#                {day_of_week: 2, activity_id: Activity.find_by_name('Katie: Eating together').id, end_time: 21, begin_time: 18},
#                {day_of_week: 3, activity_id: Activity.find_by_name('Katie: Eating together').id, end_time: 21, begin_time: 18},
#                {day_of_week: 4, activity_id: Activity.find_by_name('Katie: Eating together').id, end_time: 21, begin_time: 18},
#                {day_of_week: 5, activity_id: Activity.find_by_name('Katie: Eating together').id, end_time: 21, begin_time: 18},
#                {day_of_week: 5, activity_id: Activity.find_by_name('Katie: Eating together').id, end_time: 13, begin_time: 11},
#                {day_of_week: 6, activity_id: Activity.find_by_name('Katie: Spiritual together').id, end_time: 23, begin_time: 13},
#                {day_of_week: 0, activity_id: Activity.find_by_name('Katie: Spiritual together').id, end_time: 23, begin_time: 19},
#                {day_of_week: 1, activity_id: Activity.find_by_name('Katie: Spiritual together').id, end_time: 23, begin_time: 19},
#                {day_of_week: 2, activity_id: Activity.find_by_name('Katie: Spiritual together').id, end_time: 23, begin_time: 19},
#                {day_of_week: 3, activity_id: Activity.find_by_name('Katie: Spiritual together').id, end_time: 23, begin_time: 19},
#                {day_of_week: 4, activity_id: Activity.find_by_name('Katie: Spiritual together').id, end_time: 23, begin_time: 19},
#                {day_of_week: 5, activity_id: Activity.find_by_name('Katie: Spiritual together').id, end_time: 23, begin_time: 8},
#                {day_of_week: 6, activity_id: Activity.find_by_name('Katie: Working out/walking').id, end_time: 23, begin_time: 13},
#                {day_of_week: 0, activity_id: Activity.find_by_name('Katie: Working out/walking').id, end_time: 23, begin_time: 19},
#                {day_of_week: 1, activity_id: Activity.find_by_name('Katie: Working out/walking').id, end_time: 23, begin_time: 19},
#                {day_of_week: 2, activity_id: Activity.find_by_name('Katie: Working out/walking').id, end_time: 23, begin_time: 19},
#                {day_of_week: 3, activity_id: Activity.find_by_name('Katie: Working out/walking').id, end_time: 23, begin_time: 19},
#                {day_of_week: 4, activity_id: Activity.find_by_name('Katie: Working out/walking').id, end_time: 23, begin_time: 19},
#                {day_of_week: 5, activity_id: Activity.find_by_name('Katie: Working out/walking').id, end_time: 23, begin_time: 8},
#                {day_of_week: 6, activity_id: Activity.find_by_name('Katie: Doing things for her').id, end_time: 23, begin_time: 13},
#                {day_of_week: 0, activity_id: Activity.find_by_name('Katie: Doing things for her').id, end_time: 23, begin_time: 8},
#                {day_of_week: 1, activity_id: Activity.find_by_name('Katie: Doing things for her').id, end_time: 23, begin_time: 8},
#                {day_of_week: 2, activity_id: Activity.find_by_name('Katie: Doing things for her').id, end_time: 23, begin_time: 8},
#                {day_of_week: 3, activity_id: Activity.find_by_name('Katie: Doing things for her').id, end_time: 23, begin_time: 8},
#                {day_of_week: 4, activity_id: Activity.find_by_name('Katie: Doing things for her').id, end_time: 23, begin_time: 8},
#                {day_of_week: 5, activity_id: Activity.find_by_name('Katie: Doing things for her').id, end_time: 23, begin_time: 8},
#                {day_of_week: 6, activity_id: Activity.find_by_name('Time with friends: Talking on the phone').id, end_time: 23, begin_time: 13},
#                {day_of_week: 0, activity_id: Activity.find_by_name('Time with friends: Talking on the phone').id, end_time: 23, begin_time: 17},
#                {day_of_week: 1, activity_id: Activity.find_by_name('Time with friends: Talking on the phone').id, end_time: 23, begin_time: 17},
#                {day_of_week: 2, activity_id: Activity.find_by_name('Time with friends: Talking on the phone').id, end_time: 23, begin_time: 17},
#                {day_of_week: 3, activity_id: Activity.find_by_name('Time with friends: Talking on the phone').id, end_time: 23, begin_time: 17},
#                {day_of_week: 4, activity_id: Activity.find_by_name('Time with friends: Talking on the phone').id, end_time: 23, begin_time: 17},
#                {day_of_week: 5, activity_id: Activity.find_by_name('Time with friends: Talking on the phone').id, end_time: 23, begin_time: 11},
#                {day_of_week: 6, activity_id: Activity.find_by_name('Time with friends: Social Planning').id, end_time: 23, begin_time: 13},
#                {day_of_week: 0, activity_id: Activity.find_by_name('Time with friends: Social Planning').id, end_time: 23, begin_time: 8},
#                {day_of_week: 1, activity_id: Activity.find_by_name('Time with friends: Social Planning').id, end_time: 23, begin_time: 8},
#                {day_of_week: 2, activity_id: Activity.find_by_name('Time with friends: Social Planning').id, end_time: 23, begin_time: 8},
#                {day_of_week: 3, activity_id: Activity.find_by_name('Time with friends: Social Planning').id, end_time: 23, begin_time: 8},
#                {day_of_week: 4, activity_id: Activity.find_by_name('Time with friends: Social Planning').id, end_time: 23, begin_time: 8},
#                {day_of_week: 5, activity_id: Activity.find_by_name('Time with friends: Social Planning').id, end_time: 23, begin_time: 8},
#                {day_of_week: 6, activity_id: Activity.find_by_name('Time with friends: Email Chatting Facebook').id, end_time: 23, begin_time: 13},
#                {day_of_week: 0, activity_id: Activity.find_by_name('Time with friends: Email Chatting Facebook').id, end_time: 23, begin_time: 8},
#                {day_of_week: 1, activity_id: Activity.find_by_name('Time with friends: Email Chatting Facebook').id, end_time: 23, begin_time: 8},
#                {day_of_week: 2, activity_id: Activity.find_by_name('Time with friends: Email Chatting Facebook').id, end_time: 23, begin_time: 8},
#                {day_of_week: 3, activity_id: Activity.find_by_name('Time with friends: Email Chatting Facebook').id, end_time: 23, begin_time: 8},
#                {day_of_week: 4, activity_id: Activity.find_by_name('Time with friends: Email Chatting Facebook').id, end_time: 23, begin_time: 8},
#                {day_of_week: 5, activity_id: Activity.find_by_name('Time with friends: Email Chatting Facebook').id, end_time: 23, begin_time: 8},
#                {day_of_week: 0, activity_id: Activity.find_by_name('Routine solo work').id, end_time: 23, begin_time: 9},
#                {day_of_week: 1, activity_id: Activity.find_by_name('Routine solo work').id, end_time: 23, begin_time: 9},
#                {day_of_week: 2, activity_id: Activity.find_by_name('Routine solo work').id, end_time: 23, begin_time: 9},
#                {day_of_week: 3, activity_id: Activity.find_by_name('Routine solo work').id, end_time: 23, begin_time: 9},
#                {day_of_week: 4, activity_id: Activity.find_by_name('Routine solo work').id, end_time: 23, begin_time: 9},
#                {day_of_week: 0, activity_id: Activity.find_by_name('M&A').id, end_time: 23, begin_time: 9},
#                {day_of_week: 1, activity_id: Activity.find_by_name('M&A').id, end_time: 23, begin_time: 9},
#                {day_of_week: 2, activity_id: Activity.find_by_name('M&A').id, end_time: 23, begin_time: 9},
#                {day_of_week: 3, activity_id: Activity.find_by_name('M&A').id, end_time: 23, begin_time: 9},
#                {day_of_week: 4, activity_id: Activity.find_by_name('M&A').id, end_time: 23, begin_time: 9},
#                {day_of_week: 0, activity_id: Activity.find_by_name('Extra Projects').id, end_time: 23, begin_time: 8},
#                {day_of_week: 1, activity_id: Activity.find_by_name('Extra Projects').id, end_time: 23, begin_time: 8},
#                {day_of_week: 2, activity_id: Activity.find_by_name('Extra Projects').id, end_time: 23, begin_time: 8},
#                {day_of_week: 3, activity_id: Activity.find_by_name('Extra Projects').id, end_time: 23, begin_time: 8},
#                {day_of_week: 4, activity_id: Activity.find_by_name('Extra Projects').id, end_time: 23, begin_time: 8},
#                {day_of_week: 5, activity_id: Activity.find_by_name('Extra Projects').id, end_time: 23, begin_time: 8},
#                {day_of_week: 0, activity_id: Activity.find_by_name('Meetings').id, end_time: 17, begin_time: 8},
#                {day_of_week: 1, activity_id: Activity.find_by_name('Meetings').id, end_time: 17, begin_time: 8},
#                {day_of_week: 2, activity_id: Activity.find_by_name('Meetings').id, end_time: 17, begin_time: 8},
#                {day_of_week: 3, activity_id: Activity.find_by_name('Meetings').id, end_time: 17, begin_time: 8},
#                {day_of_week: 4, activity_id: Activity.find_by_name('Meetings').id, end_time: 17, begin_time: 8},
#                {day_of_week: 5, activity_id: Activity.find_by_name('Meetings').id, end_time: 17, begin_time: 8},
#                {day_of_week: 0, activity_id: Activity.find_by_name('Email').id, end_time: 23, begin_time: 8},
#                {day_of_week: 1, activity_id: Activity.find_by_name('Email').id, end_time: 23, begin_time: 8},
#                {day_of_week: 2, activity_id: Activity.find_by_name('Email').id, end_time: 23, begin_time: 8},
#                {day_of_week: 3, activity_id: Activity.find_by_name('Email').id, end_time: 23, begin_time: 8},
#                {day_of_week: 4, activity_id: Activity.find_by_name('Email').id, end_time: 23, begin_time: 8},
#                {day_of_week: 5, activity_id: Activity.find_by_name('Email').id, end_time: 23, begin_time: 8},
#                {day_of_week: 0, activity_id: Activity.find_by_name('Networking').id, end_time: 17, begin_time: 8},
#                {day_of_week: 1, activity_id: Activity.find_by_name('Networking').id, end_time: 17, begin_time: 8},
#                {day_of_week: 2, activity_id: Activity.find_by_name('Networking').id, end_time: 17, begin_time: 8},
#                {day_of_week: 3, activity_id: Activity.find_by_name('Networking').id, end_time: 17, begin_time: 8},
#                {day_of_week: 4, activity_id: Activity.find_by_name('Networking').id, end_time: 17, begin_time: 8},
#                {day_of_week: 5, activity_id: Activity.find_by_name('Networking').id, end_time: 17, begin_time: 8},
#                {day_of_week: 0, activity_id: Activity.find_by_name('New Projects').id, end_time: 23, begin_time: 8},
#                {day_of_week: 1, activity_id: Activity.find_by_name('New Projects').id, end_time: 23, begin_time: 8},
#                {day_of_week: 2, activity_id: Activity.find_by_name('New Projects').id, end_time: 23, begin_time: 8},
#                {day_of_week: 3, activity_id: Activity.find_by_name('New Projects').id, end_time: 23, begin_time: 8},
#                {day_of_week: 4, activity_id: Activity.find_by_name('New Projects').id, end_time: 23, begin_time: 8},
#                {day_of_week: 5, activity_id: Activity.find_by_name('New Projects').id, end_time: 23, begin_time: 8},
#                {day_of_week: 6, activity_id: Activity.find_by_name('Development Learning').id, end_time: 23, begin_time: 13},
#                {day_of_week: 0, activity_id: Activity.find_by_name('Development Learning').id, end_time: 23, begin_time: 6},
#                {day_of_week: 1, activity_id: Activity.find_by_name('Development Learning').id, end_time: 23, begin_time: 6},
#                {day_of_week: 2, activity_id: Activity.find_by_name('Development Learning').id, end_time: 23, begin_time: 6},
#                {day_of_week: 3, activity_id: Activity.find_by_name('Development Learning').id, end_time: 23, begin_time: 6},
#                {day_of_week: 4, activity_id: Activity.find_by_name('Development Learning').id, end_time: 23, begin_time: 6},
#                {day_of_week: 5, activity_id: Activity.find_by_name('Development Learning').id, end_time: 23, begin_time: 6},
#                {day_of_week: 0, activity_id: Activity.find_by_name('Programming').id, end_time: 23, begin_time: 6},
#                {day_of_week: 1, activity_id: Activity.find_by_name('Programming').id, end_time: 23, begin_time: 6},
#                {day_of_week: 2, activity_id: Activity.find_by_name('Programming').id, end_time: 23, begin_time: 6},
#                {day_of_week: 3, activity_id: Activity.find_by_name('Programming').id, end_time: 23, begin_time: 6},
#                {day_of_week: 4, activity_id: Activity.find_by_name('Programming').id, end_time: 23, begin_time: 6},
#                {day_of_week: 5, activity_id: Activity.find_by_name('Programming').id, end_time: 23, begin_time: 6},
#                {day_of_week: 6, activity_id: Activity.find_by_name('Financials').id, end_time: 23, begin_time: 13},
#                {day_of_week: 0, activity_id: Activity.find_by_name('Financials').id, end_time: 23, begin_time: 6},
#                {day_of_week: 1, activity_id: Activity.find_by_name('Financials').id, end_time: 23, begin_time: 6},
#                {day_of_week: 2, activity_id: Activity.find_by_name('Financials').id, end_time: 23, begin_time: 6},
#                {day_of_week: 3, activity_id: Activity.find_by_name('Financials').id, end_time: 23, begin_time: 6},
#                {day_of_week: 4, activity_id: Activity.find_by_name('Financials').id, end_time: 23, begin_time: 6},
#                {day_of_week: 5, activity_id: Activity.find_by_name('Financials').id, end_time: 23, begin_time: 6},
#                {day_of_week: 6, activity_id: Activity.find_by_name('Calendar').id, end_time: 23, begin_time: 13},
#                {day_of_week: 0, activity_id: Activity.find_by_name('Calendar').id, end_time: 23, begin_time: 6},
#                {day_of_week: 1, activity_id: Activity.find_by_name('Calendar').id, end_time: 23, begin_time: 6},
#                {day_of_week: 2, activity_id: Activity.find_by_name('Calendar').id, end_time: 23, begin_time: 6},
#                {day_of_week: 3, activity_id: Activity.find_by_name('Calendar').id, end_time: 23, begin_time: 6},
#                {day_of_week: 4, activity_id: Activity.find_by_name('Calendar').id, end_time: 23, begin_time: 6},
#                {day_of_week: 5, activity_id: Activity.find_by_name('Calendar').id, end_time: 23, begin_time: 6},
#                {day_of_week: 6, activity_id: Activity.find_by_name('Design').id, end_time: 23, begin_time: 13},
#                {day_of_week: 0, activity_id: Activity.find_by_name('Design').id, end_time: 23, begin_time: 6},
#                {day_of_week: 1, activity_id: Activity.find_by_name('Design').id, end_time: 23, begin_time: 6},
#                {day_of_week: 2, activity_id: Activity.find_by_name('Design').id, end_time: 23, begin_time: 6},
#                {day_of_week: 3, activity_id: Activity.find_by_name('Design').id, end_time: 23, begin_time: 6},
#                {day_of_week: 4, activity_id: Activity.find_by_name('Design').id, end_time: 23, begin_time: 6},
#                {day_of_week: 5, activity_id: Activity.find_by_name('Design').id, end_time: 23, begin_time: 6},
#                {day_of_week: 6, activity_id: Activity.find_by_name('Singing').id, end_time: 23, begin_time: 13},
#                {day_of_week: 0, activity_id: Activity.find_by_name('Singing').id, end_time: 20, begin_time: 8},
#                {day_of_week: 1, activity_id: Activity.find_by_name('Singing').id, end_time: 20, begin_time: 8},
#                {day_of_week: 2, activity_id: Activity.find_by_name('Singing').id, end_time: 20, begin_time: 8},
#                {day_of_week: 3, activity_id: Activity.find_by_name('Singing').id, end_time: 20, begin_time: 8},
#                {day_of_week: 4, activity_id: Activity.find_by_name('Singing').id, end_time: 20, begin_time: 8},
#                {day_of_week: 5, activity_id: Activity.find_by_name('Singing').id, end_time: 20, begin_time: 8},
#                {day_of_week: 6, activity_id: Activity.find_by_name('Clean').id, end_time: 23, begin_time: 13},
#                {day_of_week: 0, activity_id: Activity.find_by_name('Clean').id, end_time: 23, begin_time: 6},
#                {day_of_week: 1, activity_id: Activity.find_by_name('Clean').id, end_time: 23, begin_time: 6},
#                {day_of_week: 2, activity_id: Activity.find_by_name('Clean').id, end_time: 23, begin_time: 6},
#                {day_of_week: 3, activity_id: Activity.find_by_name('Clean').id, end_time: 23, begin_time: 6},
#                {day_of_week: 4, activity_id: Activity.find_by_name('Clean').id, end_time: 23, begin_time: 6},
#                {day_of_week: 5, activity_id: Activity.find_by_name('Clean').id, end_time: 23, begin_time: 6},
#                {day_of_week: 6, activity_id: Activity.find_by_name('Shop').id, end_time: 23, begin_time: 13},
#                {day_of_week: 0, activity_id: Activity.find_by_name('Shop').id, end_time: 20, begin_time: 8},
#                {day_of_week: 1, activity_id: Activity.find_by_name('Shop').id, end_time: 20, begin_time: 8},
#                {day_of_week: 2, activity_id: Activity.find_by_name('Shop').id, end_time: 20, begin_time: 8},
#                {day_of_week: 3, activity_id: Activity.find_by_name('Shop').id, end_time: 20, begin_time: 8},
#                {day_of_week: 4, activity_id: Activity.find_by_name('Shop').id, end_time: 20, begin_time: 8},
#                {day_of_week: 5, activity_id: Activity.find_by_name('Shop').id, end_time: 20, begin_time: 8},
#                {day_of_week: 6, activity_id: Activity.find_by_name('Scriptures').id, end_time: 23, begin_time: 6},
#                {day_of_week: 0, activity_id: Activity.find_by_name('Scriptures').id, end_time: 23, begin_time: 6},
#                {day_of_week: 1, activity_id: Activity.find_by_name('Scriptures').id, end_time: 23, begin_time: 6},
#                {day_of_week: 2, activity_id: Activity.find_by_name('Scriptures').id, end_time: 23, begin_time: 6},
#                {day_of_week: 3, activity_id: Activity.find_by_name('Scriptures').id, end_time: 23, begin_time: 6},
#                {day_of_week: 4, activity_id: Activity.find_by_name('Scriptures').id, end_time: 23, begin_time: 6},
#                {day_of_week: 5, activity_id: Activity.find_by_name('Scriptures').id, end_time: 23, begin_time: 6},
#                {day_of_week: 6, activity_id: Activity.find_by_name('Journal Photos').id, end_time: 23, begin_time: 6},
#                {day_of_week: 0, activity_id: Activity.find_by_name('Journal Photos').id, end_time: 23, begin_time: 6},
#                {day_of_week: 1, activity_id: Activity.find_by_name('Journal Photos').id, end_time: 23, begin_time: 6},
#                {day_of_week: 2, activity_id: Activity.find_by_name('Journal Photos').id, end_time: 23, begin_time: 6},
#                {day_of_week: 3, activity_id: Activity.find_by_name('Journal Photos').id, end_time: 23, begin_time: 6},
#                {day_of_week: 4, activity_id: Activity.find_by_name('Journal Photos').id, end_time: 23, begin_time: 6},
#                {day_of_week: 5, activity_id: Activity.find_by_name('Journal Photos').id, end_time: 23, begin_time: 6},
#                {day_of_week: 6, activity_id: Activity.find_by_name('Exercise').id, end_time: 23, begin_time: 6},
#                {day_of_week: 0, activity_id: Activity.find_by_name('Exercise').id, end_time: 23, begin_time: 6},
#                {day_of_week: 1, activity_id: Activity.find_by_name('Exercise').id, end_time: 23, begin_time: 6},
#                {day_of_week: 2, activity_id: Activity.find_by_name('Exercise').id, end_time: 23, begin_time: 6},
#                {day_of_week: 3, activity_id: Activity.find_by_name('Exercise').id, end_time: 23, begin_time: 6},
#                {day_of_week: 4, activity_id: Activity.find_by_name('Exercise').id, end_time: 23, begin_time: 6},
#                {day_of_week: 5, activity_id: Activity.find_by_name('Exercise').id, end_time: 23, begin_time: 6},
#                {day_of_week: 0, activity_id: Activity.find_by_name('Read wsj or bus mag').id, end_time: 23, begin_time: 6},
#                {day_of_week: 1, activity_id: Activity.find_by_name('Read wsj or bus mag').id, end_time: 23, begin_time: 6},
#                {day_of_week: 2, activity_id: Activity.find_by_name('Read wsj or bus mag').id, end_time: 23, begin_time: 6},
#                {day_of_week: 3, activity_id: Activity.find_by_name('Read wsj or bus mag').id, end_time: 23, begin_time: 6},
#                {day_of_week: 4, activity_id: Activity.find_by_name('Read wsj or bus mag').id, end_time: 23, begin_time: 6},
#                {day_of_week: 5, activity_id: Activity.find_by_name('Read wsj or bus mag').id, end_time: 23, begin_time: 6},
#                {day_of_week: 6, activity_id: Activity.find_by_name('Internet surfing').id, end_time: 23, begin_time: 6},
#                {day_of_week: 0, activity_id: Activity.find_by_name('Internet surfing').id, end_time: 23, begin_time: 6},
#                {day_of_week: 1, activity_id: Activity.find_by_name('Internet surfing').id, end_time: 23, begin_time: 6},
#                {day_of_week: 2, activity_id: Activity.find_by_name('Internet surfing').id, end_time: 23, begin_time: 6},
#                {day_of_week: 3, activity_id: Activity.find_by_name('Internet surfing').id, end_time: 23, begin_time: 6},
#                {day_of_week: 4, activity_id: Activity.find_by_name('Internet surfing').id, end_time: 23, begin_time: 6},
#                {day_of_week: 5, activity_id: Activity.find_by_name('Internet surfing').id, end_time: 23, begin_time: 6},
#                {day_of_week: 6, activity_id: Activity.find_by_name('Time Wasters').id, end_time: 23, begin_time: 6},
#                {day_of_week: 0, activity_id: Activity.find_by_name('Time Wasters').id, end_time: 23, begin_time: 6},
#                {day_of_week: 1, activity_id: Activity.find_by_name('Time Wasters').id, end_time: 23, begin_time: 6},
#                {day_of_week: 2, activity_id: Activity.find_by_name('Time Wasters').id, end_time: 23, begin_time: 6},
#                {day_of_week: 3, activity_id: Activity.find_by_name('Time Wasters').id, end_time: 23, begin_time: 6},
#                {day_of_week: 4, activity_id: Activity.find_by_name('Time Wasters').id, end_time: 23, begin_time: 6},
#                {day_of_week: 5, activity_id: Activity.find_by_name('Time Wasters').id, end_time: 23, begin_time: 6},
#                {day_of_week: 6, activity_id: Activity.find_by_name('Music').id, end_time: 23, begin_time: 6},
#                {day_of_week: 0, activity_id: Activity.find_by_name('Music').id, end_time: 23, begin_time: 6},
#                {day_of_week: 1, activity_id: Activity.find_by_name('Music').id, end_time: 23, begin_time: 6},
#                {day_of_week: 2, activity_id: Activity.find_by_name('Music').id, end_time: 23, begin_time: 6},
#                {day_of_week: 3, activity_id: Activity.find_by_name('Music').id, end_time: 23, begin_time: 6},
#                {day_of_week: 4, activity_id: Activity.find_by_name('Music').id, end_time: 23, begin_time: 6},
#                {day_of_week: 5, activity_id: Activity.find_by_name('Music').id, end_time: 23, begin_time: 6},
#                {day_of_week: 6, activity_id: Activity.find_by_name('Concert or Movie').id, end_time: 23, begin_time: 6},
#                {day_of_week: 0, activity_id: Activity.find_by_name('Concert or Movie').id, end_time: 23, begin_time: 6},
#                {day_of_week: 1, activity_id: Activity.find_by_name('Concert or Movie').id, end_time: 23, begin_time: 6},
#                {day_of_week: 2, activity_id: Activity.find_by_name('Concert or Movie').id, end_time: 23, begin_time: 6},
#                {day_of_week: 3, activity_id: Activity.find_by_name('Concert or Movie').id, end_time: 23, begin_time: 6},
#                {day_of_week: 4, activity_id: Activity.find_by_name('Concert or Movie').id, end_time: 23, begin_time: 6},
#                {day_of_week: 5, activity_id: Activity.find_by_name('Concert or Movie').id, end_time: 23, begin_time: 6},
#                {day_of_week: 6, activity_id: Activity.find_by_name('Reading').id, end_time: 23, begin_time: 6},
#                {day_of_week: 0, activity_id: Activity.find_by_name('Reading').id, end_time: 23, begin_time: 6},
#                {day_of_week: 1, activity_id: Activity.find_by_name('Reading').id, end_time: 23, begin_time: 6},
#                {day_of_week: 2, activity_id: Activity.find_by_name('Reading').id, end_time: 23, begin_time: 6},
#                {day_of_week: 3, activity_id: Activity.find_by_name('Reading').id, end_time: 23, begin_time: 6},
#                {day_of_week: 4, activity_id: Activity.find_by_name('Reading').id, end_time: 23, begin_time: 6},
#                {day_of_week: 5, activity_id: Activity.find_by_name('Reading').id, end_time: 23, begin_time: 6},
#                {day_of_week: 0, activity_id: Activity.find_by_name('Experience New York').id, end_time: 23, begin_time: 17},
#                {day_of_week: 1, activity_id: Activity.find_by_name('Experience New York').id, end_time: 23, begin_time: 17},
#                {day_of_week: 2, activity_id: Activity.find_by_name('Experience New York').id, end_time: 23, begin_time: 17},
#                {day_of_week: 3, activity_id: Activity.find_by_name('Experience New York').id, end_time: 23, begin_time: 17},
#                {day_of_week: 4, activity_id: Activity.find_by_name('Experience New York').id, end_time: 23, begin_time: 17},
#                {day_of_week: 5, activity_id: Activity.find_by_name('Experience New York').id, end_time: 23, begin_time: 6},
#                {day_of_week: 6, activity_id: Activity.find_by_name('Sleep').id, end_time: 7, begin_time: 0},
#                {day_of_week: 0, activity_id: Activity.find_by_name('Sleep').id, end_time: 7, begin_time: 0},
#                {day_of_week: 1, activity_id: Activity.find_by_name('Sleep').id, end_time: 7, begin_time: 0},
#                {day_of_week: 2, activity_id: Activity.find_by_name('Sleep').id, end_time: 7, begin_time: 0},
#                {day_of_week: 3, activity_id: Activity.find_by_name('Sleep').id, end_time: 7, begin_time: 0},
#                {day_of_week: 4, activity_id: Activity.find_by_name('Sleep').id, end_time: 7, begin_time: 0},
#                {day_of_week: 5, activity_id: Activity.find_by_name('Sleep').id, end_time: 7, begin_time: 0},
#                {day_of_week: 6, activity_id: Activity.find_by_name('Sleep').id, end_time: 23, begin_time: 22},
#                {day_of_week: 0, activity_id: Activity.find_by_name('Sleep').id, end_time: 23, begin_time: 22},
#                {day_of_week: 1, activity_id: Activity.find_by_name('Sleep').id, end_time: 23, begin_time: 22},
#                {day_of_week: 2, activity_id: Activity.find_by_name('Sleep').id, end_time: 23, begin_time: 22},
#                {day_of_week: 3, activity_id: Activity.find_by_name('Sleep').id, end_time: 23, begin_time: 22},
#                {day_of_week: 4, activity_id: Activity.find_by_name('Sleep').id, end_time: 23, begin_time: 22},
#                {day_of_week: 5, activity_id: Activity.find_by_name('Sleep').id, end_time: 23, begin_time: 22}])
#
#WeeklyPlan.create!([{start_date: Time.new(2013, 4, 22), activity_id: Activity.find_by_name('Katie: Having fun').id, number_of_hours: 2},
#                    {start_date: Time.new(2013, 4, 22), activity_id: Activity.find_by_name('Katie: Making out').id, number_of_hours: 3},
#                    {start_date: Time.new(2013, 4, 22), activity_id: Activity.find_by_name('Katie: Eating together').id, number_of_hours: 2},
#                    {start_date: Time.new(2013, 4, 22), activity_id: Activity.find_by_name('Katie: Time with friends').id, number_of_hours: 6},
#                    {start_date: Time.new(2013, 4, 22), activity_id: Activity.find_by_name('Time with friends: Talking on the phone').id, number_of_hours: 2.5},
#                    {start_date: Time.new(2013, 4, 22), activity_id: Activity.find_by_name('Time with friends: Weekend hanging out').id, number_of_hours: 6.5},
#                    {start_date: Time.new(2013, 4, 22), activity_id: Activity.find_by_name('Time with friends: Sunday hanging out').id, number_of_hours: 0.5},
#                    {start_date: Time.new(2013, 4, 22), activity_id: Activity.find_by_name('Time with friends: Social Planning').id, number_of_hours: 1},
#                    {start_date: Time.new(2013, 4, 22), activity_id: Activity.find_by_name('Extra Projects').id, number_of_hours: 36},
#                    {start_date: Time.new(2013, 4, 22), activity_id: Activity.find_by_name('Meetings').id, number_of_hours: 2},
#                    {start_date: Time.new(2013, 4, 22), activity_id: Activity.find_by_name('New Projects').id, number_of_hours: 5},
#                    {start_date: Time.new(2013, 4, 22), activity_id: Activity.find_by_name('Programming').id, number_of_hours: 18.5},
#                    {start_date: Time.new(2013, 4, 22), activity_id: Activity.find_by_name('Calendar').id, number_of_hours: 0.5},
#                    {start_date: Time.new(2013, 4, 22), activity_id: Activity.find_by_name('Design').id, number_of_hours: 2},
#                    {start_date: Time.new(2013, 4, 22), activity_id: Activity.find_by_name('Singing').id, number_of_hours: 1.5},
#                    {start_date: Time.new(2013, 4, 22), activity_id: Activity.find_by_name('Shop').id, number_of_hours: 0.5},
#                    {start_date: Time.new(2013, 4, 22), activity_id: Activity.find_by_name('Scriptures').id, number_of_hours: 0.5},
#                    {start_date: Time.new(2013, 4, 22), activity_id: Activity.find_by_name('Church').id, number_of_hours: 7.5},
#                    {start_date: Time.new(2013, 4, 22), activity_id: Activity.find_by_name('Journal Photos').id, number_of_hours: 1.5},
#                    {start_date: Time.new(2013, 4, 22), activity_id: Activity.find_by_name('Exercise').id, number_of_hours: 2},
#                    {start_date: Time.new(2013, 4, 22), activity_id: Activity.find_by_name('getready').id, number_of_hours: 3.5},
#                    {start_date: Time.new(2013, 4, 22), activity_id: Activity.find_by_name('Read wsj or bus mag').id, number_of_hours: 2.5},
#                    {start_date: Time.new(2013, 4, 22), activity_id: Activity.find_by_name('Internet surfing').id, number_of_hours: 0.5},
#                    {start_date: Time.new(2013, 4, 22), activity_id: Activity.find_by_name('Time Wasters').id, number_of_hours: 3},
#                    {start_date: Time.new(2013, 4, 22), activity_id: Activity.find_by_name('Music').id, number_of_hours: 1.5},
#                    {start_date: Time.new(2013, 4, 22), activity_id: Activity.find_by_name('Concert or Movie').id, number_of_hours: 2.5},
#                    {start_date: Time.new(2013, 4, 22), activity_id: Activity.find_by_name('Experience New York').id, number_of_hours: 6},
#                    {start_date: Time.new(2013, 4, 22), activity_id: Activity.find_by_name('Sleep').id, number_of_hours: 47}])