# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)
 Category.create!([{name: 'Sleep & Relaxation'},
                              {name: 'Time with Katie'},
                              {name: 'Social'},
                              {name: 'Work'},
                              {name: 'Solo Entertainment'},
                              {name: 'Physical'},
                              {name: 'Spiritual'},
                              {name: 'Everyday tasks'},
                              {name: 'Development & Leadership'}])

Activity.create!([{name: 'Almost Sleep', category_id: Category.find_by_name( 'Time with Katie').id, repeating: TRUE},
                              {name: 'Meditate', category_id: Category.find_by_name( 'Time with Katie').id, repeating: TRUE},
                              {name: 'Katie: Having fun', category_id: Category.find_by_name( 'Social').id, repeating: TRUE},
                              {name: 'Katie: Concert Movie Art', category_id: Category.find_by_name( 'Social').id, repeating: TRUE},
                              {name: 'Katie: Talking', category_id: Category.find_by_name( 'Social').id, repeating: TRUE},
                              {name: 'Katie: Making out', category_id: Category.find_by_name( 'Social').id, repeating: TRUE},
                              {name: 'Katie: Working together', category_id: Category.find_by_name( 'Social').id, repeating: TRUE},
                              {name: 'Katie: Eating together', category_id: Category.find_by_name( 'Social').id, repeating: TRUE},
                              {name: 'Katie: Sitting together', category_id: Category.find_by_name( 'Social').id, repeating: TRUE},
                              {name: 'Katie: Spiritual together', category_id: Category.find_by_name( 'Social').id, repeating: TRUE},
                              {name: 'Katie: Working out/walking', category_id: Category.find_by_name( 'Social').id, repeating: TRUE},
                              {name: 'Katie: Doing things for her', category_id: Category.find_by_name( 'Social').id, repeating: TRUE},
                              {name: 'Katie: Time with friends', category_id: Category.find_by_name( 'Social').id, repeating: TRUE},
                              {name: 'Time with Family', category_id: Category.find_by_name( 'Social').id, repeating: TRUE},
                              {name: 'Time with friends: Talking on the phone', category_id: Category.find_by_name( 'Work').id, repeating: TRUE},
                              {name: 'Time with friends: Concert Movie Art', category_id: Category.find_by_name( 'Work').id, repeating: TRUE},
                              {name: 'Time with friends: Weekday hanging out', category_id: Category.find_by_name( 'Work').id, repeating: TRUE},
                              {name: 'Time with friends: Weekend hanging out', category_id: Category.find_by_name( 'Work').id, repeating: TRUE},
                              {name: 'Time with friends: Sunday hanging out', category_id: Category.find_by_name( 'Work').id, repeating: TRUE},
                              {name: 'Time with friends: Social Planning', category_id: Category.find_by_name( 'Work').id, repeating: TRUE},
                              {name: 'Time with friends: Email Chatting Facebook', category_id: Category.find_by_name( 'Work').id, repeating: TRUE},
                              {name: 'Routine solo work', category_id: Category.find_by_name( 'Solo Entertainment').id, repeating: TRUE},
                              {name: 'M&A', category_id: Category.find_by_name( 'Solo Entertainment').id, repeating: TRUE},
                              {name: 'Extra Projects', category_id: Category.find_by_name( 'Solo Entertainment').id, repeating: TRUE},
                              {name: 'Meetings', category_id: Category.find_by_name( 'Solo Entertainment').id, repeating: TRUE},
                              {name: 'Email', category_id: Category.find_by_name( 'Solo Entertainment').id, repeating: TRUE},
                              {name: 'Networking', category_id: Category.find_by_name( 'Solo Entertainment').id, repeating: TRUE},
                              {name: 'New Projects', category_id: Category.find_by_name( 'Solo Entertainment').id, repeating: TRUE},
                              {name: 'Development Learning', category_id: Category.find_by_name( 'Solo Entertainment').id, repeating: TRUE},
                              {name: 'Programming', category_id: Category.find_by_name( 'Solo Entertainment').id, repeating: TRUE},
                              {name: 'Commute', category_id: Category.find_by_name( 'Physical').id, repeating: TRUE},
                              {name: 'Financials', category_id: Category.find_by_name( 'Physical').id, repeating: TRUE},
                              {name: 'Calendar', category_id: Category.find_by_name( 'Development & Leadership').id, repeating: TRUE},
                              {name: 'Design', category_id: Category.find_by_name( 'Development & Leadership').id, repeating: TRUE},
                              {name: 'Singing', category_id: Category.find_by_name( 'Development & Leadership').id, repeating: TRUE},
                              {name: 'Clean', category_id: Category.find_by_name( 'Development & Leadership').id, repeating: TRUE},
                              {name: 'Shop', category_id: Category.find_by_name( 'Development & Leadership').id, repeating: TRUE},
                              {name: 'Scriptures', category_id: Category.find_by_name( 'Everyday tasks').id, repeating: TRUE},
                              {name: 'Church', category_id: Category.find_by_name( 'Everyday tasks').id, repeating: TRUE},
                              {name: 'Leadership Service', category_id: Category.find_by_name( 'Development & Leadership').id, repeating: TRUE},
                              {name: 'Journal Photos', category_id: Category.find_by_name( 'Development & Leadership').id, repeating: TRUE},
                              {name: 'Exercise', category_id: Category.find_by_name( 'Spiritual').id, repeating: TRUE},
                              {name: 'getready', category_id: Category.find_by_name( 'Spiritual').id, repeating: TRUE},
                              {name: 'Eating alone', category_id: Category.find_by_name( 'Spiritual').id, repeating: TRUE},
                              {name: 'Read wsj or bus mag', category_id: Category.find_by_name( 'Physical').id, repeating: TRUE},
                              {name: 'Internet surfing', category_id: Category.find_by_name( 'Physical').id, repeating: TRUE},
                              {name: 'Time Wasters', category_id: Category.find_by_name( 'Physical').id, repeating: TRUE},
                              {name: 'Music', category_id: Category.find_by_name( 'Physical').id, repeating: TRUE},
                              {name: 'Concert or Movie', category_id: Category.find_by_name( 'Physical').id, repeating: TRUE},
                              {name: 'Reading', category_id: Category.find_by_name( 'Physical').id, repeating: TRUE},
                              {name: 'Experience New York', category_id: Category.find_by_name( 'Physical').id, repeating: TRUE},
                              {name: 'Sleep', category_id: Category.find_by_name( 'Time with Katie').id, repeating: TRUE}])

Window.create!([{ day_of_week: 6, activity_id: Activity.find_by_name( 'Katie: Having fun').id, end_time: 23, begin_time: 13 },
                         { day_of_week: 0, activity_id: Activity.find_by_name( 'Katie: Having fun').id, end_time: 23, begin_time: 19 },
                         { day_of_week: 1, activity_id: Activity.find_by_name( 'Katie: Having fun').id, end_time: 23, begin_time: 19 },
                         { day_of_week: 2, activity_id: Activity.find_by_name( 'Katie: Having fun').id, end_time: 23, begin_time: 19 },
                         { day_of_week: 3, activity_id: Activity.find_by_name( 'Katie: Having fun').id, end_time: 23, begin_time: 19 },
                         { day_of_week: 4, activity_id: Activity.find_by_name( 'Katie: Having fun').id, end_time: 23, begin_time: 19 },
                         { day_of_week: 5, activity_id: Activity.find_by_name( 'Katie: Having fun').id, end_time: 23, begin_time: 8 },
                         { day_of_week: 6, activity_id: Activity.find_by_name( 'Katie: Concert Movie Art').id, end_time: 23, begin_time: 13 },
                         { day_of_week: 0, activity_id: Activity.find_by_name( 'Katie: Concert Movie Art').id, end_time: 23, begin_time: 19 },
                         { day_of_week: 1, activity_id: Activity.find_by_name( 'Katie: Concert Movie Art').id, end_time: 23, begin_time: 19 },
                         { day_of_week: 2, activity_id: Activity.find_by_name( 'Katie: Concert Movie Art').id, end_time: 23, begin_time: 19 },
                         { day_of_week: 3, activity_id: Activity.find_by_name( 'Katie: Concert Movie Art').id, end_time: 23, begin_time: 19 },
                         { day_of_week: 4, activity_id: Activity.find_by_name( 'Katie: Concert Movie Art').id, end_time: 23, begin_time: 19 },
                         { day_of_week: 5, activity_id: Activity.find_by_name( 'Katie: Concert Movie Art').id, end_time: 23, begin_time: 8 },
                         { day_of_week: 6, activity_id: Activity.find_by_name( 'Katie: Talking').id, end_time: 23, begin_time: 13 },
                         { day_of_week: 0, activity_id: Activity.find_by_name( 'Katie: Talking').id, end_time: 23, begin_time: 19 },
                         { day_of_week: 1, activity_id: Activity.find_by_name( 'Katie: Talking').id, end_time: 23, begin_time: 19 },
                         { day_of_week: 2, activity_id: Activity.find_by_name( 'Katie: Talking').id, end_time: 23, begin_time: 19 },
                         { day_of_week: 3, activity_id: Activity.find_by_name( 'Katie: Talking').id, end_time: 23, begin_time: 19 },
                         { day_of_week: 4, activity_id: Activity.find_by_name( 'Katie: Talking').id, end_time: 23, begin_time: 19 },
                         { day_of_week: 5, activity_id: Activity.find_by_name( 'Katie: Talking').id, end_time: 23, begin_time: 8 },
                         { day_of_week: 6, activity_id: Activity.find_by_name( 'Katie: Making out').id, end_time: 23, begin_time: 13 },
                         { day_of_week: 0, activity_id: Activity.find_by_name( 'Katie: Making out').id, end_time: 23, begin_time: 19 },
                         { day_of_week: 1, activity_id: Activity.find_by_name( 'Katie: Making out').id, end_time: 23, begin_time: 19 },
                         { day_of_week: 2, activity_id: Activity.find_by_name( 'Katie: Making out').id, end_time: 23, begin_time: 19 },
                         { day_of_week: 3, activity_id: Activity.find_by_name( 'Katie: Making out').id, end_time: 23, begin_time: 19 },
                         { day_of_week: 4, activity_id: Activity.find_by_name( 'Katie: Making out').id, end_time: 23, begin_time: 19 },
                         { day_of_week: 5, activity_id: Activity.find_by_name( 'Katie: Making out').id, end_time: 23, begin_time: 8 },
                         { day_of_week: 0, activity_id: Activity.find_by_name( 'Katie: Working together').id, end_time: 23, begin_time: 19 },
                         { day_of_week: 1, activity_id: Activity.find_by_name( 'Katie: Working together').id, end_time: 23, begin_time: 19 },
                         { day_of_week: 2, activity_id: Activity.find_by_name( 'Katie: Working together').id, end_time: 23, begin_time: 19 },
                         { day_of_week: 3, activity_id: Activity.find_by_name( 'Katie: Working together').id, end_time: 23, begin_time: 19 },
                         { day_of_week: 4, activity_id: Activity.find_by_name( 'Katie: Working together').id, end_time: 23, begin_time: 19 },
                         { day_of_week: 5, activity_id: Activity.find_by_name( 'Katie: Working together').id, end_time: 23, begin_time: 8 },
                         { day_of_week: 6, activity_id: Activity.find_by_name( 'Katie: Eating together').id, end_time: 21, begin_time: 18 },
                         { day_of_week: 6, activity_id: Activity.find_by_name( 'Katie: Eating together').id, end_time: 15, begin_time: 13 },
                         { day_of_week: 0, activity_id: Activity.find_by_name( 'Katie: Eating together').id, end_time: 21, begin_time: 18 },
                         { day_of_week: 1, activity_id: Activity.find_by_name( 'Katie: Eating together').id, end_time: 21, begin_time: 18 },
                         { day_of_week: 2, activity_id: Activity.find_by_name( 'Katie: Eating together').id, end_time: 21, begin_time: 18 },
                         { day_of_week: 3, activity_id: Activity.find_by_name( 'Katie: Eating together').id, end_time: 21, begin_time: 18 },
                         { day_of_week: 4, activity_id: Activity.find_by_name( 'Katie: Eating together').id, end_time: 21, begin_time: 18 },
                         { day_of_week: 5, activity_id: Activity.find_by_name( 'Katie: Eating together').id, end_time: 21, begin_time: 18 },
                         { day_of_week: 5, activity_id: Activity.find_by_name( 'Katie: Eating together').id, end_time: 13, begin_time: 11 },
                         { day_of_week: 6, activity_id: Activity.find_by_name( 'Katie: Spiritual together').id, end_time: 23, begin_time: 13 },
                         { day_of_week: 0, activity_id: Activity.find_by_name( 'Katie: Spiritual together').id, end_time: 23, begin_time: 19 },
                         { day_of_week: 1, activity_id: Activity.find_by_name( 'Katie: Spiritual together').id, end_time: 23, begin_time: 19 },
                         { day_of_week: 2, activity_id: Activity.find_by_name( 'Katie: Spiritual together').id, end_time: 23, begin_time: 19 },
                         { day_of_week: 3, activity_id: Activity.find_by_name( 'Katie: Spiritual together').id, end_time: 23, begin_time: 19 },
                         { day_of_week: 4, activity_id: Activity.find_by_name( 'Katie: Spiritual together').id, end_time: 23, begin_time: 19 },
                         { day_of_week: 5, activity_id: Activity.find_by_name( 'Katie: Spiritual together').id, end_time: 23, begin_time: 8 },
                         { day_of_week: 6, activity_id: Activity.find_by_name( 'Katie: Working out/walking').id, end_time: 23, begin_time: 13 },
                         { day_of_week: 0, activity_id: Activity.find_by_name( 'Katie: Working out/walking').id, end_time: 23, begin_time: 19 },
                         { day_of_week: 1, activity_id: Activity.find_by_name( 'Katie: Working out/walking').id, end_time: 23, begin_time: 19 },
                         { day_of_week: 2, activity_id: Activity.find_by_name( 'Katie: Working out/walking').id, end_time: 23, begin_time: 19 },
                         { day_of_week: 3, activity_id: Activity.find_by_name( 'Katie: Working out/walking').id, end_time: 23, begin_time: 19 },
                         { day_of_week: 4, activity_id: Activity.find_by_name( 'Katie: Working out/walking').id, end_time: 23, begin_time: 19 },
                         { day_of_week: 5, activity_id: Activity.find_by_name( 'Katie: Working out/walking').id, end_time: 23, begin_time: 8 },
                         { day_of_week: 6, activity_id: Activity.find_by_name( 'Katie: Doing things for her').id, end_time: 23, begin_time: 13 },
                         { day_of_week: 0, activity_id: Activity.find_by_name( 'Katie: Doing things for her').id, end_time: 23, begin_time: 8 },
                         { day_of_week: 1, activity_id: Activity.find_by_name( 'Katie: Doing things for her').id, end_time: 23, begin_time: 8 },
                         { day_of_week: 2, activity_id: Activity.find_by_name( 'Katie: Doing things for her').id, end_time: 23, begin_time: 8 },
                         { day_of_week: 3, activity_id: Activity.find_by_name( 'Katie: Doing things for her').id, end_time: 23, begin_time: 8 },
                         { day_of_week: 4, activity_id: Activity.find_by_name( 'Katie: Doing things for her').id, end_time: 23, begin_time: 8 },
                         { day_of_week: 5, activity_id: Activity.find_by_name( 'Katie: Doing things for her').id, end_time: 23, begin_time: 8 },
                         { day_of_week: 6, activity_id: Activity.find_by_name( 'Time with friends: Talking on the phone').id, end_time: 23, begin_time: 13 },
                         { day_of_week: 0, activity_id: Activity.find_by_name( 'Time with friends: Talking on the phone').id, end_time: 23, begin_time: 17 },
                         { day_of_week: 1, activity_id: Activity.find_by_name( 'Time with friends: Talking on the phone').id, end_time: 23, begin_time: 17 },
                         { day_of_week: 2, activity_id: Activity.find_by_name( 'Time with friends: Talking on the phone').id, end_time: 23, begin_time: 17 },
                         { day_of_week: 3, activity_id: Activity.find_by_name( 'Time with friends: Talking on the phone').id, end_time: 23, begin_time: 17 },
                         { day_of_week: 4, activity_id: Activity.find_by_name( 'Time with friends: Talking on the phone').id, end_time: 23, begin_time: 17 },
                         { day_of_week: 5, activity_id: Activity.find_by_name( 'Time with friends: Talking on the phone').id, end_time: 23, begin_time: 11 },
                         { day_of_week: 6, activity_id: Activity.find_by_name( 'Time with friends: Social Planning').id, end_time: 23, begin_time: 13 },
                         { day_of_week: 0, activity_id: Activity.find_by_name( 'Time with friends: Social Planning').id, end_time: 23, begin_time: 8 },
                         { day_of_week: 1, activity_id: Activity.find_by_name( 'Time with friends: Social Planning').id, end_time: 23, begin_time: 8 },
                         { day_of_week: 2, activity_id: Activity.find_by_name( 'Time with friends: Social Planning').id, end_time: 23, begin_time: 8 },
                         { day_of_week: 3, activity_id: Activity.find_by_name( 'Time with friends: Social Planning').id, end_time: 23, begin_time: 8 },
                         { day_of_week: 4, activity_id: Activity.find_by_name( 'Time with friends: Social Planning').id, end_time: 23, begin_time: 8 },
                         { day_of_week: 5, activity_id: Activity.find_by_name( 'Time with friends: Social Planning').id, end_time: 23, begin_time: 8 },
                         { day_of_week: 6, activity_id: Activity.find_by_name( 'Time with friends: Email Chatting Facebook').id, end_time: 23, begin_time: 13 },
                         { day_of_week: 0, activity_id: Activity.find_by_name( 'Time with friends: Email Chatting Facebook').id, end_time: 23, begin_time: 8 },
                         { day_of_week: 1, activity_id: Activity.find_by_name( 'Time with friends: Email Chatting Facebook').id, end_time: 23, begin_time: 8 },
                         { day_of_week: 2, activity_id: Activity.find_by_name( 'Time with friends: Email Chatting Facebook').id, end_time: 23, begin_time: 8 },
                         { day_of_week: 3, activity_id: Activity.find_by_name( 'Time with friends: Email Chatting Facebook').id, end_time: 23, begin_time: 8 },
                         { day_of_week: 4, activity_id: Activity.find_by_name( 'Time with friends: Email Chatting Facebook').id, end_time: 23, begin_time: 8 },
                         { day_of_week: 5, activity_id: Activity.find_by_name( 'Time with friends: Email Chatting Facebook').id, end_time: 23, begin_time: 8 },
                         { day_of_week: 0, activity_id: Activity.find_by_name( 'Routine solo work').id, end_time: 23, begin_time: 9 },
                         { day_of_week: 1, activity_id: Activity.find_by_name( 'Routine solo work').id, end_time: 23, begin_time: 9 },
                         { day_of_week: 2, activity_id: Activity.find_by_name( 'Routine solo work').id, end_time: 23, begin_time: 9 },
                         { day_of_week: 3, activity_id: Activity.find_by_name( 'Routine solo work').id, end_time: 23, begin_time: 9 },
                         { day_of_week: 4, activity_id: Activity.find_by_name( 'Routine solo work').id, end_time: 23, begin_time: 9 },
                         { day_of_week: 0, activity_id: Activity.find_by_name( 'M&A').id, end_time: 23, begin_time: 9 },
                         { day_of_week: 1, activity_id: Activity.find_by_name( 'M&A').id, end_time: 23, begin_time: 9 },
                         { day_of_week: 2, activity_id: Activity.find_by_name( 'M&A').id, end_time: 23, begin_time: 9 },
                         { day_of_week: 3, activity_id: Activity.find_by_name( 'M&A').id, end_time: 23, begin_time: 9 },
                         { day_of_week: 4, activity_id: Activity.find_by_name( 'M&A').id, end_time: 23, begin_time: 9 },
                         { day_of_week: 0, activity_id: Activity.find_by_name( 'Extra Projects').id, end_time: 23, begin_time: 8 },
                         { day_of_week: 1, activity_id: Activity.find_by_name( 'Extra Projects').id, end_time: 23, begin_time: 8 },
                         { day_of_week: 2, activity_id: Activity.find_by_name( 'Extra Projects').id, end_time: 23, begin_time: 8 },
                         { day_of_week: 3, activity_id: Activity.find_by_name( 'Extra Projects').id, end_time: 23, begin_time: 8 },
                         { day_of_week: 4, activity_id: Activity.find_by_name( 'Extra Projects').id, end_time: 23, begin_time: 8 },
                         { day_of_week: 5, activity_id: Activity.find_by_name( 'Extra Projects').id, end_time: 23, begin_time: 8 },
                         { day_of_week: 0, activity_id: Activity.find_by_name( 'Meetings').id, end_time: 17, begin_time: 8 },
                         { day_of_week: 1, activity_id: Activity.find_by_name( 'Meetings').id, end_time: 17, begin_time: 8 },
                         { day_of_week: 2, activity_id: Activity.find_by_name( 'Meetings').id, end_time: 17, begin_time: 8 },
                         { day_of_week: 3, activity_id: Activity.find_by_name( 'Meetings').id, end_time: 17, begin_time: 8 },
                         { day_of_week: 4, activity_id: Activity.find_by_name( 'Meetings').id, end_time: 17, begin_time: 8 },
                         { day_of_week: 5, activity_id: Activity.find_by_name( 'Meetings').id, end_time: 17, begin_time: 8 },
                         { day_of_week: 0, activity_id: Activity.find_by_name( 'Email').id, end_time: 23, begin_time: 8 },
                         { day_of_week: 1, activity_id: Activity.find_by_name( 'Email').id, end_time: 23, begin_time: 8 },
                         { day_of_week: 2, activity_id: Activity.find_by_name( 'Email').id, end_time: 23, begin_time: 8 },
                         { day_of_week: 3, activity_id: Activity.find_by_name( 'Email').id, end_time: 23, begin_time: 8 },
                         { day_of_week: 4, activity_id: Activity.find_by_name( 'Email').id, end_time: 23, begin_time: 8 },
                         { day_of_week: 5, activity_id: Activity.find_by_name( 'Email').id, end_time: 23, begin_time: 8 },
                         { day_of_week: 0, activity_id: Activity.find_by_name( 'Networking').id, end_time: 17, begin_time: 8 },
                         { day_of_week: 1, activity_id: Activity.find_by_name( 'Networking').id, end_time: 17, begin_time: 8 },
                         { day_of_week: 2, activity_id: Activity.find_by_name( 'Networking').id, end_time: 17, begin_time: 8 },
                         { day_of_week: 3, activity_id: Activity.find_by_name( 'Networking').id, end_time: 17, begin_time: 8 },
                         { day_of_week: 4, activity_id: Activity.find_by_name( 'Networking').id, end_time: 17, begin_time: 8 },
                         { day_of_week: 5, activity_id: Activity.find_by_name( 'Networking').id, end_time: 17, begin_time: 8 },
                         { day_of_week: 0, activity_id: Activity.find_by_name( 'New Projects').id, end_time: 23, begin_time: 8 },
                         { day_of_week: 1, activity_id: Activity.find_by_name( 'New Projects').id, end_time: 23, begin_time: 8 },
                         { day_of_week: 2, activity_id: Activity.find_by_name( 'New Projects').id, end_time: 23, begin_time: 8 },
                         { day_of_week: 3, activity_id: Activity.find_by_name( 'New Projects').id, end_time: 23, begin_time: 8 },
                         { day_of_week: 4, activity_id: Activity.find_by_name( 'New Projects').id, end_time: 23, begin_time: 8 },
                         { day_of_week: 5, activity_id: Activity.find_by_name( 'New Projects').id, end_time: 23, begin_time: 8 },
                         { day_of_week: 6, activity_id: Activity.find_by_name( 'Development Learning').id, end_time: 23, begin_time: 13 },
                         { day_of_week: 0, activity_id: Activity.find_by_name( 'Development Learning').id, end_time: 23, begin_time: 6 },
                         { day_of_week: 1, activity_id: Activity.find_by_name( 'Development Learning').id, end_time: 23, begin_time: 6 },
                         { day_of_week: 2, activity_id: Activity.find_by_name( 'Development Learning').id, end_time: 23, begin_time: 6 },
                         { day_of_week: 3, activity_id: Activity.find_by_name( 'Development Learning').id, end_time: 23, begin_time: 6 },
                         { day_of_week: 4, activity_id: Activity.find_by_name( 'Development Learning').id, end_time: 23, begin_time: 6 },
                         { day_of_week: 5, activity_id: Activity.find_by_name( 'Development Learning').id, end_time: 23, begin_time: 6 },
                         { day_of_week: 0, activity_id: Activity.find_by_name( 'Programming').id, end_time: 23, begin_time: 6 },
                         { day_of_week: 1, activity_id: Activity.find_by_name( 'Programming').id, end_time: 23, begin_time: 6 },
                         { day_of_week: 2, activity_id: Activity.find_by_name( 'Programming').id, end_time: 23, begin_time: 6 },
                         { day_of_week: 3, activity_id: Activity.find_by_name( 'Programming').id, end_time: 23, begin_time: 6 },
                         { day_of_week: 4, activity_id: Activity.find_by_name( 'Programming').id, end_time: 23, begin_time: 6 },
                         { day_of_week: 5, activity_id: Activity.find_by_name( 'Programming').id, end_time: 23, begin_time: 6 },
                         { day_of_week: 6, activity_id: Activity.find_by_name( 'Financials').id, end_time: 23, begin_time: 13 },
                         { day_of_week: 0, activity_id: Activity.find_by_name( 'Financials').id, end_time: 23, begin_time: 6 },
                         { day_of_week: 1, activity_id: Activity.find_by_name( 'Financials').id, end_time: 23, begin_time: 6 },
                         { day_of_week: 2, activity_id: Activity.find_by_name( 'Financials').id, end_time: 23, begin_time: 6 },
                         { day_of_week: 3, activity_id: Activity.find_by_name( 'Financials').id, end_time: 23, begin_time: 6 },
                         { day_of_week: 4, activity_id: Activity.find_by_name( 'Financials').id, end_time: 23, begin_time: 6 },
                         { day_of_week: 5, activity_id: Activity.find_by_name( 'Financials').id, end_time: 23, begin_time: 6 },
                         { day_of_week: 6, activity_id: Activity.find_by_name( 'Calendar').id, end_time: 23, begin_time: 13 },
                         { day_of_week: 0, activity_id: Activity.find_by_name( 'Calendar').id, end_time: 23, begin_time: 6 },
                         { day_of_week: 1, activity_id: Activity.find_by_name( 'Calendar').id, end_time: 23, begin_time: 6 },
                         { day_of_week: 2, activity_id: Activity.find_by_name( 'Calendar').id, end_time: 23, begin_time: 6 },
                         { day_of_week: 3, activity_id: Activity.find_by_name( 'Calendar').id, end_time: 23, begin_time: 6 },
                         { day_of_week: 4, activity_id: Activity.find_by_name( 'Calendar').id, end_time: 23, begin_time: 6 },
                         { day_of_week: 5, activity_id: Activity.find_by_name( 'Calendar').id, end_time: 23, begin_time: 6 },
                         { day_of_week: 6, activity_id: Activity.find_by_name( 'Design').id, end_time: 23, begin_time: 13 },
                         { day_of_week: 0, activity_id: Activity.find_by_name( 'Design').id, end_time: 23, begin_time: 6 },
                         { day_of_week: 1, activity_id: Activity.find_by_name( 'Design').id, end_time: 23, begin_time: 6 },
                         { day_of_week: 2, activity_id: Activity.find_by_name( 'Design').id, end_time: 23, begin_time: 6 },
                         { day_of_week: 3, activity_id: Activity.find_by_name( 'Design').id, end_time: 23, begin_time: 6 },
                         { day_of_week: 4, activity_id: Activity.find_by_name( 'Design').id, end_time: 23, begin_time: 6 },
                         { day_of_week: 5, activity_id: Activity.find_by_name( 'Design').id, end_time: 23, begin_time: 6 },
                         { day_of_week: 6, activity_id: Activity.find_by_name( 'Singing').id, end_time: 23, begin_time: 13 },
                         { day_of_week: 0, activity_id: Activity.find_by_name( 'Singing').id, end_time: 20, begin_time: 8 },
                         { day_of_week: 1, activity_id: Activity.find_by_name( 'Singing').id, end_time: 20, begin_time: 8 },
                         { day_of_week: 2, activity_id: Activity.find_by_name( 'Singing').id, end_time: 20, begin_time: 8 },
                         { day_of_week: 3, activity_id: Activity.find_by_name( 'Singing').id, end_time: 20, begin_time: 8 },
                         { day_of_week: 4, activity_id: Activity.find_by_name( 'Singing').id, end_time: 20, begin_time: 8 },
                         { day_of_week: 5, activity_id: Activity.find_by_name( 'Singing').id, end_time: 20, begin_time: 8 },
                         { day_of_week: 6, activity_id: Activity.find_by_name( 'Clean').id, end_time: 23, begin_time: 13 },
                         { day_of_week: 0, activity_id: Activity.find_by_name( 'Clean').id, end_time: 23, begin_time: 6 },
                         { day_of_week: 1, activity_id: Activity.find_by_name( 'Clean').id, end_time: 23, begin_time: 6 },
                         { day_of_week: 2, activity_id: Activity.find_by_name( 'Clean').id, end_time: 23, begin_time: 6 },
                         { day_of_week: 3, activity_id: Activity.find_by_name( 'Clean').id, end_time: 23, begin_time: 6 },
                         { day_of_week: 4, activity_id: Activity.find_by_name( 'Clean').id, end_time: 23, begin_time: 6 },
                         { day_of_week: 5, activity_id: Activity.find_by_name( 'Clean').id, end_time: 23, begin_time: 6 },
                         { day_of_week: 6, activity_id: Activity.find_by_name( 'Shop').id, end_time: 23, begin_time: 13 },
                         { day_of_week: 0, activity_id: Activity.find_by_name( 'Shop').id, end_time: 20, begin_time: 8 },
                         { day_of_week: 1, activity_id: Activity.find_by_name( 'Shop').id, end_time: 20, begin_time: 8 },
                         { day_of_week: 2, activity_id: Activity.find_by_name( 'Shop').id, end_time: 20, begin_time: 8 },
                         { day_of_week: 3, activity_id: Activity.find_by_name( 'Shop').id, end_time: 20, begin_time: 8 },
                         { day_of_week: 4, activity_id: Activity.find_by_name( 'Shop').id, end_time: 20, begin_time: 8 },
                         { day_of_week: 5, activity_id: Activity.find_by_name( 'Shop').id, end_time: 20, begin_time: 8 },
                         { day_of_week: 6, activity_id: Activity.find_by_name( 'Scriptures').id, end_time: 23, begin_time: 6 },
                         { day_of_week: 0, activity_id: Activity.find_by_name( 'Scriptures').id, end_time: 23, begin_time: 6 },
                         { day_of_week: 1, activity_id: Activity.find_by_name( 'Scriptures').id, end_time: 23, begin_time: 6 },
                         { day_of_week: 2, activity_id: Activity.find_by_name( 'Scriptures').id, end_time: 23, begin_time: 6 },
                         { day_of_week: 3, activity_id: Activity.find_by_name( 'Scriptures').id, end_time: 23, begin_time: 6 },
                         { day_of_week: 4, activity_id: Activity.find_by_name( 'Scriptures').id, end_time: 23, begin_time: 6 },
                         { day_of_week: 5, activity_id: Activity.find_by_name( 'Scriptures').id, end_time: 23, begin_time: 6 },
                         { day_of_week: 6, activity_id: Activity.find_by_name( 'Journal Photos').id, end_time: 23, begin_time: 6 },
                         { day_of_week: 0, activity_id: Activity.find_by_name( 'Journal Photos').id, end_time: 23, begin_time: 6 },
                         { day_of_week: 1, activity_id: Activity.find_by_name( 'Journal Photos').id, end_time: 23, begin_time: 6 },
                         { day_of_week: 2, activity_id: Activity.find_by_name( 'Journal Photos').id, end_time: 23, begin_time: 6 },
                         { day_of_week: 3, activity_id: Activity.find_by_name( 'Journal Photos').id, end_time: 23, begin_time: 6 },
                         { day_of_week: 4, activity_id: Activity.find_by_name( 'Journal Photos').id, end_time: 23, begin_time: 6 },
                         { day_of_week: 5, activity_id: Activity.find_by_name( 'Journal Photos').id, end_time: 23, begin_time: 6 },
                         { day_of_week: 6, activity_id: Activity.find_by_name( 'Exercise').id, end_time: 23, begin_time: 6 },
                         { day_of_week: 0, activity_id: Activity.find_by_name( 'Exercise').id, end_time: 23, begin_time: 6 },
                         { day_of_week: 1, activity_id: Activity.find_by_name( 'Exercise').id, end_time: 23, begin_time: 6 },
                         { day_of_week: 2, activity_id: Activity.find_by_name( 'Exercise').id, end_time: 23, begin_time: 6 },
                         { day_of_week: 3, activity_id: Activity.find_by_name( 'Exercise').id, end_time: 23, begin_time: 6 },
                         { day_of_week: 4, activity_id: Activity.find_by_name( 'Exercise').id, end_time: 23, begin_time: 6 },
                         { day_of_week: 5, activity_id: Activity.find_by_name( 'Exercise').id, end_time: 23, begin_time: 6 },
                         { day_of_week: 0, activity_id: Activity.find_by_name( 'Read wsj or bus mag').id, end_time: 23, begin_time: 6 },
                         { day_of_week: 1, activity_id: Activity.find_by_name( 'Read wsj or bus mag').id, end_time: 23, begin_time: 6 },
                         { day_of_week: 2, activity_id: Activity.find_by_name( 'Read wsj or bus mag').id, end_time: 23, begin_time: 6 },
                         { day_of_week: 3, activity_id: Activity.find_by_name( 'Read wsj or bus mag').id, end_time: 23, begin_time: 6 },
                         { day_of_week: 4, activity_id: Activity.find_by_name( 'Read wsj or bus mag').id, end_time: 23, begin_time: 6 },
                         { day_of_week: 5, activity_id: Activity.find_by_name( 'Read wsj or bus mag').id, end_time: 23, begin_time: 6 },
                         { day_of_week: 6, activity_id: Activity.find_by_name( 'Internet surfing').id, end_time: 23, begin_time: 6 },
                         { day_of_week: 0, activity_id: Activity.find_by_name( 'Internet surfing').id, end_time: 23, begin_time: 6 },
                         { day_of_week: 1, activity_id: Activity.find_by_name( 'Internet surfing').id, end_time: 23, begin_time: 6 },
                         { day_of_week: 2, activity_id: Activity.find_by_name( 'Internet surfing').id, end_time: 23, begin_time: 6 },
                         { day_of_week: 3, activity_id: Activity.find_by_name( 'Internet surfing').id, end_time: 23, begin_time: 6 },
                         { day_of_week: 4, activity_id: Activity.find_by_name( 'Internet surfing').id, end_time: 23, begin_time: 6 },
                         { day_of_week: 5, activity_id: Activity.find_by_name( 'Internet surfing').id, end_time: 23, begin_time: 6 },
                         { day_of_week: 6, activity_id: Activity.find_by_name( 'Time Wasters').id, end_time: 23, begin_time: 6 },
                         { day_of_week: 0, activity_id: Activity.find_by_name( 'Time Wasters').id, end_time: 23, begin_time: 6 },
                         { day_of_week: 1, activity_id: Activity.find_by_name( 'Time Wasters').id, end_time: 23, begin_time: 6 },
                         { day_of_week: 2, activity_id: Activity.find_by_name( 'Time Wasters').id, end_time: 23, begin_time: 6 },
                         { day_of_week: 3, activity_id: Activity.find_by_name( 'Time Wasters').id, end_time: 23, begin_time: 6 },
                         { day_of_week: 4, activity_id: Activity.find_by_name( 'Time Wasters').id, end_time: 23, begin_time: 6 },
                         { day_of_week: 5, activity_id: Activity.find_by_name( 'Time Wasters').id, end_time: 23, begin_time: 6 },
                         { day_of_week: 6, activity_id: Activity.find_by_name( 'Music').id, end_time: 23, begin_time: 6 },
                         { day_of_week: 0, activity_id: Activity.find_by_name( 'Music').id, end_time: 23, begin_time: 6 },
                         { day_of_week: 1, activity_id: Activity.find_by_name( 'Music').id, end_time: 23, begin_time: 6 },
                         { day_of_week: 2, activity_id: Activity.find_by_name( 'Music').id, end_time: 23, begin_time: 6 },
                         { day_of_week: 3, activity_id: Activity.find_by_name( 'Music').id, end_time: 23, begin_time: 6 },
                         { day_of_week: 4, activity_id: Activity.find_by_name( 'Music').id, end_time: 23, begin_time: 6 },
                         { day_of_week: 5, activity_id: Activity.find_by_name( 'Music').id, end_time: 23, begin_time: 6 },
                         { day_of_week: 6, activity_id: Activity.find_by_name( 'Concert or Movie').id, end_time: 23, begin_time: 6 },
                         { day_of_week: 0, activity_id: Activity.find_by_name( 'Concert or Movie').id, end_time: 23, begin_time: 6 },
                         { day_of_week: 1, activity_id: Activity.find_by_name( 'Concert or Movie').id, end_time: 23, begin_time: 6 },
                         { day_of_week: 2, activity_id: Activity.find_by_name( 'Concert or Movie').id, end_time: 23, begin_time: 6 },
                         { day_of_week: 3, activity_id: Activity.find_by_name( 'Concert or Movie').id, end_time: 23, begin_time: 6 },
                         { day_of_week: 4, activity_id: Activity.find_by_name( 'Concert or Movie').id, end_time: 23, begin_time: 6 },
                         { day_of_week: 5, activity_id: Activity.find_by_name( 'Concert or Movie').id, end_time: 23, begin_time: 6 },
                         { day_of_week: 6, activity_id: Activity.find_by_name( 'Reading').id, end_time: 23, begin_time: 6 },
                         { day_of_week: 0, activity_id: Activity.find_by_name( 'Reading').id, end_time: 23, begin_time: 6 },
                         { day_of_week: 1, activity_id: Activity.find_by_name( 'Reading').id, end_time: 23, begin_time: 6 },
                         { day_of_week: 2, activity_id: Activity.find_by_name( 'Reading').id, end_time: 23, begin_time: 6 },
                         { day_of_week: 3, activity_id: Activity.find_by_name( 'Reading').id, end_time: 23, begin_time: 6 },
                         { day_of_week: 4, activity_id: Activity.find_by_name( 'Reading').id, end_time: 23, begin_time: 6 },
                         { day_of_week: 5, activity_id: Activity.find_by_name( 'Reading').id, end_time: 23, begin_time: 6 },
                         { day_of_week: 0, activity_id: Activity.find_by_name( 'Experience New York').id, end_time: 23, begin_time: 17 },
                         { day_of_week: 1, activity_id: Activity.find_by_name( 'Experience New York').id, end_time: 23, begin_time: 17 },
                         { day_of_week: 2, activity_id: Activity.find_by_name( 'Experience New York').id, end_time: 23, begin_time: 17 },
                         { day_of_week: 3, activity_id: Activity.find_by_name( 'Experience New York').id, end_time: 23, begin_time: 17 },
                         { day_of_week: 4, activity_id: Activity.find_by_name( 'Experience New York').id, end_time: 23, begin_time: 17 },
                         { day_of_week: 5, activity_id: Activity.find_by_name( 'Experience New York').id, end_time: 23, begin_time: 6 },
                         { day_of_week: 6, activity_id: Activity.find_by_name( 'Sleep').id, end_time: 7, begin_time: 0 },
                         { day_of_week: 0, activity_id: Activity.find_by_name( 'Sleep').id, end_time: 7, begin_time: 0 },
                         { day_of_week: 1, activity_id: Activity.find_by_name( 'Sleep').id, end_time: 7, begin_time: 0 },
                         { day_of_week: 2, activity_id: Activity.find_by_name( 'Sleep').id, end_time: 7, begin_time: 0 },
                         { day_of_week: 3, activity_id: Activity.find_by_name( 'Sleep').id, end_time: 7, begin_time: 0 },
                         { day_of_week: 4, activity_id: Activity.find_by_name( 'Sleep').id, end_time: 7, begin_time: 0 },
                         { day_of_week: 5, activity_id: Activity.find_by_name( 'Sleep').id, end_time: 7, begin_time: 0 },
                         { day_of_week: 6, activity_id: Activity.find_by_name( 'Sleep').id, end_time: 23, begin_time: 22 },
                         { day_of_week: 0, activity_id: Activity.find_by_name( 'Sleep').id, end_time: 23, begin_time: 22 },
                         { day_of_week: 1, activity_id: Activity.find_by_name( 'Sleep').id, end_time: 23, begin_time: 22 },
                         { day_of_week: 2, activity_id: Activity.find_by_name( 'Sleep').id, end_time: 23, begin_time: 22 },
                         { day_of_week: 3, activity_id: Activity.find_by_name( 'Sleep').id, end_time: 23, begin_time: 22 },
                         { day_of_week: 4, activity_id: Activity.find_by_name( 'Sleep').id, end_time: 23, begin_time: 22 },
                         { day_of_week: 5, activity_id: Activity.find_by_name( 'Sleep').id, end_time: 23, begin_time: 22 }])

WeeklyPlan.create!([{ start_date: Time.new(2013,4,22), activity_id: Activity.find_by_name( 'Katie: Having fun').id, number_of_hours: 2 },
                    { start_date: Time.new(2013,4,22), activity_id: Activity.find_by_name( 'Katie: Making out').id, number_of_hours: 3 },
                    { start_date: Time.new(2013,4,22), activity_id: Activity.find_by_name( 'Katie: Eating together').id, number_of_hours: 2 },
                    { start_date: Time.new(2013,4,22), activity_id: Activity.find_by_name( 'Katie: Time with friends').id, number_of_hours: 6 },
                    { start_date: Time.new(2013,4,22), activity_id: Activity.find_by_name( 'Time with friends: Talking on the phone').id, number_of_hours: 2.5 },
                    { start_date: Time.new(2013,4,22), activity_id: Activity.find_by_name( 'Time with friends: Weekend hanging out').id, number_of_hours: 6.5 },
                    { start_date: Time.new(2013,4,22), activity_id: Activity.find_by_name( 'Time with friends: Sunday hanging out').id, number_of_hours: 0.5 },
                    { start_date: Time.new(2013,4,22), activity_id: Activity.find_by_name( 'Time with friends: Social Planning').id, number_of_hours: 1 },
                    { start_date: Time.new(2013,4,22), activity_id: Activity.find_by_name( 'Extra Projects').id, number_of_hours: 36 },
                    { start_date: Time.new(2013,4,22), activity_id: Activity.find_by_name( 'Meetings').id, number_of_hours: 2 },
                    { start_date: Time.new(2013,4,22), activity_id: Activity.find_by_name( 'New Projects').id, number_of_hours: 5 },
                    { start_date: Time.new(2013,4,22), activity_id: Activity.find_by_name( 'Programming').id, number_of_hours: 18.5 },
                    { start_date: Time.new(2013,4,22), activity_id: Activity.find_by_name( 'Calendar').id, number_of_hours: 0.5 },
                    { start_date: Time.new(2013,4,22), activity_id: Activity.find_by_name( 'Design').id, number_of_hours: 2 },
                    { start_date: Time.new(2013,4,22), activity_id: Activity.find_by_name( 'Singing').id, number_of_hours: 1.5 },
                    { start_date: Time.new(2013,4,22), activity_id: Activity.find_by_name( 'Shop').id, number_of_hours: 0.5 },
                    { start_date: Time.new(2013,4,22), activity_id: Activity.find_by_name( 'Scriptures').id, number_of_hours: 0.5 },
                    { start_date: Time.new(2013,4,22), activity_id: Activity.find_by_name( 'Church').id, number_of_hours: 7.5 },
                    { start_date: Time.new(2013,4,22), activity_id: Activity.find_by_name( 'Journal Photos').id, number_of_hours: 1.5 },
                    { start_date: Time.new(2013,4,22), activity_id: Activity.find_by_name( 'Exercise').id, number_of_hours: 2 },
                    { start_date: Time.new(2013,4,22), activity_id: Activity.find_by_name( 'getready').id, number_of_hours: 3.5 },
                    { start_date: Time.new(2013,4,22), activity_id: Activity.find_by_name( 'Read wsj or bus mag').id, number_of_hours: 2.5 },
                    { start_date: Time.new(2013,4,22), activity_id: Activity.find_by_name( 'Internet surfing').id, number_of_hours: 0.5 },
                    { start_date: Time.new(2013,4,22), activity_id: Activity.find_by_name( 'Time Wasters').id, number_of_hours: 3 },
                    { start_date: Time.new(2013,4,22), activity_id: Activity.find_by_name( 'Music').id, number_of_hours: 1.5 },
                    { start_date: Time.new(2013,4,22), activity_id: Activity.find_by_name( 'Concert or Movie').id, number_of_hours: 2.5 },
                    { start_date: Time.new(2013,4,22), activity_id: Activity.find_by_name( 'Experience New York').id, number_of_hours: 6 },
                    { start_date: Time.new(2013,4,22), activity_id: Activity.find_by_name( 'Sleep').id, number_of_hours: 47 }])